[package]
name = "servare"
description = "The Servare service"
version = "0.1.0"
edition = "2021"
authors = ["Vincent Rischmann"]
license = "Proprietary"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "servare"

[dependencies]
# Error stuff
thiserror = "1"
anyhow = "1"

# SQL on steroids
sqlx = { version = "0.6", default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "time", "migrate", "offline"] }
