[application]
worker_threads = 4
host = "127.0.0.1"
port = 4052
base_url = "http://127.0.0.1"
cookie_signing_key = "1a730b845426442ce64762fbd20930360a9c5099095b3275f6f89cb6b7f164fc5a35c5a9e26092692f914805fe6022ed1ed5e2a94570c25d3d31b8831c02b822"

[job]
run_interval_seconds = 10

[session]
ttl_seconds = 604800
cleanup_enabled = true
cleanup_interval_seconds = 3600

[database]
username = "vincent"
password = "vincent"
port = 5432
host = "127.0.0.1"
name = "servare_tests"

[tem]
base_url = "https://api.scaleway.com/transactional-email/v1alpha1/regions/fr-par"
project_id = "myprojectid"
auth_key = "myauthkey"
sender_email = "vincent@rischmann.fr"
timeout_milliseconds = 10000

[jaeger]
host = "127.0.0.1"
port = 6831

[tracing.targets]
logging = [
    "sqlx=error",
    "servare=trace",
    "info",
]
jaeger = [
    "sqlx=error",
    "info",
]
