ALTER TABLE feeds ALTER COLUMN title SET NOT NULL;
ALTER TABLE feeds ALTER COLUMN site_link SET NOT NULL;
ALTER TABLE feeds ALTER COLUMN description SET NOT NULL;
ALTER TABLE feeds ALTER COLUMN last_checked_at SET NOT NULL;
